worker_processes 1;
events { worker_connections 1024; }

http {
    server {
        listen 8080;

        # Balik sa Google para sa ibang path (pagtatago)
        location / {
            proxy_pass https://www.google.com;
            proxy_set_header Host www.google.com;
            proxy_ssl_server_name on;
            proxy_ssl_name www.google.com;
        }

        # Trojan-WS
        location /virgozki {
            proxy_pass http://127.0.0.1:10000;
            proxy_http_version 1.1;
            proxy_set_header Upgrade $http_upgrade;
            proxy_set_header Connection "upgrade";
            proxy_set_header Host $host;
            proxy_cache_bypass $http_upgrade;
        }

        # Trojan-HTTPUpgrade
        location /virgozki {
            proxy_pass http://127.0.0.1:10001;
            proxy_http_version 1.1;
            proxy_set_header Upgrade $http_upgrade;
            proxy_set_header Connection "upgrade";
            proxy_set_header Host $host;
        }

        # Trojan-XHTTP
        location /virgozki {
            proxy_pass http://127.0.0.1:10002;
            proxy_set_header Host $host;
        }
    }
}

