worker_processes 1;
events { worker_connections 1024; }
http {
  server {
    listen 8080;
    location / {
      proxy_pass https://www.google.com;
      proxy_set_header Host www.google.com;
      proxy_ssl_server_name on;
    }

    # Trojan-WS
    location /virgozki {
      proxy_pass http://127.0.0.1:10000;
      proxy_http_version 1.1;
      proxy_set_header Upgrade $http_upgrade;
      proxy_set_header Connection "upgrade";
      proxy_set_header Host $host;
      proxy_ssl_server_name on;
    }

    # Trojan-gRPC
    location /virgozki/ {
      proxy_pass http://127.0.0.1:10001/;
      proxy_http_version 2;
      proxy_set_header TE "trailers";
      proxy_set_header Host $host;
      proxy_ssl_server_name on;
    }

    # Trojan-HTTPUpgrade
    location /virgozki-upgrade {
      proxy_pass http://127.0.0.1:10002;
      proxy_http_version 1.1;
      proxy_set_header Upgrade $http_upgrade;
      proxy_set_header Connection "upgrade";
      proxy_set_header Host $host;
      proxy_ssl_server_name on;
    }

    # Trojan-XHTTP
    location /virgozki-xhttp {
      proxy_pass http://127.0.0.1:10003;
      proxy_set_header Host $host;
      proxy_ssl_server_name on;
    }
  }
}
